/*
 * Archivo de Conversiones de datos
 * Campos Rodriguez y Lopez Vega
 * Práctica 4b RPC (función de 2 parámetros)
 * Please do not edit this file, generated using rpcgen.
 */


#include "suma.h"

bool_t
xdr_dupla_int (XDR *xdrs, dupla_int *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}
